server:
  port: 8080
  servlet:
    context-path: /
spring:
  redis:
    database: 0
    timeout: 6000ms
    cluster:
      nodes:
        - 127.0.0.1:6379
        - 127.0.0.1:6380
        - 127.0.0.1:6381
        - 127.0.0.1:6382
        - 127.0.0.1:6383
        - 127.0.0.1:6384
      max-redirects: 3
    lettuce:
      pool:
        max-active: 100
        max-idle: 10
        min-idle: 2
        max-wait: -1
